version: '3.8'

services:
  web:
    build: .
    container_name: document_rag_matrix
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=cyberpunk-prod-secret-matrix-999
      - ALLOWED_HOSTS=*
      - LLM_PROVIDER=auto
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./media:/app/media
      - ./db_data:/app/data
