# Generated by Django 6.0.5 on 2026-08-29 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Cyberpunk Dialogue Matrix', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(default='txt', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('total_characters', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Matrix Upload'), ('processing', 'Processing & Vectorizing'), ('indexed', 'Fully Indexed & Online'), ('failed', 'Vectorization Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User / Operator'), ('assistant', 'Cyber AI Assistant'), ('system', 'System / Matrix Protocol')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list, help_text='Retrieved chunks and similarity metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag_app.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='rag_app.document'),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, help_text='Float array representation of vector', null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag_app.document')),
            ],
            options={
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='rag_app_doc_documen_bc68dc_idx')],
            },
        ),
    ]
