# Generated by Django 6.0.5 on 2026-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='structure_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='topics_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
